before_install:
  - gem update bundler rake
branches:
  only:
    - master
    - v2
language: ruby
matrix:
  allow_failures:
    - rvm: "2.1"
    - rvm: ruby-head
rvm:
  - "2.1"
  - "2.2"
  - "2.3"
  - "2.4"
  - ruby-head
script: bundle exec rspec
sudo: false
