before_install:
  - rvm get head
  - gem update bundler rake
branches:
  only:
    - master
    - v2
cache: bundler
language: ruby
matrix:
  allow_failures:
    - rvm: ruby-head
rvm:
  - "2.0"
  - "2.1"
  - "2.2"
  - "2.3"
  - ruby-head
script: bundle exec rspec
sudo: false
